### ISSUE TITLE
Menu doesn't work on internet explorer

### ISSUE THREAD

**Issue by CecileVava** [edinburghtoollibrary/spanner#3]
When they click on the menu in the top left corner, nothing happens. 
They were using Internet Explorer.
There is an example on Hotjar if that can help @tbartels. Let me know.

**Comment by tbartels** [comment]
any idea which version of IE?

**Comment by tbartels** [comment]
Looks like it was an error in a different script that was causing all of the JS to break, I've added a small contingency to try and prevent this from happening ever again, should be working now.
