### ISSUE TITLE
Search engines results show pages from the old website

### ISSUE THREAD

**Issue by CecileVava** [edinburghtoollibrary/spanner#5]
In google search results, the sub-pages are for the old website and don't work and/or aren't relevant. See below: Contact, ETL Network and Story are from the old website.
https://www.google.co.uk/search?q=Edinburgh+tool+library
![Capture d’écran 2020-04-14 à 12 07 04](https://user-images.githubusercontent.com/63102629/79219276-ddf8bd80-7e49-11ea-89f0-92c1bc2fb3bc.png)

In Ecosia search results, there is a similar problem. It might be the same on other search engines too. Happy to test the most common ones if needed. 
https://www.ecosia.org/search?q=Edinburgh+Tool+Library
![Capture d’écran 2020-04-14 à 12 19 25](https://user-images.githubusercontent.com/63102629/79219457-392ab000-7e4a-11ea-8c0e-8ff4c83640b5.png)

**Comment by tbartels** [comment]
These are just a product of changing up the website structure, the search engines will update and see the new locations once they start indexing the site again. It looks like google has already been updated and most of ecosia has as well. I'll be doing a review of 404s in the coming weeks to see what hasn't been converted, or what's left as dead links out in the world.
