### ISSUE TITLE
IDEA/ Designing and developping an accordion widget

### ISSUE THREAD

**Issue by CecileVava** [edinburghtoollibrary/spanner#9]
This would be super useful for the list of current volunteering opportunities
![Capture d’écran 2020-05-29 à 17 22 11](https://user-images.githubusercontent.com/63102629/83282479-8e8c0800-a1d1-11ea-8710-586b865ebba0.png)
![Capture d’écran 2020-05-29 à 17 22 33](https://user-images.githubusercontent.com/63102629/83282485-90ee6200-a1d1-11ea-8506-7f723dd26103.png)

**Comment by CecileVava** [comment]
and for the F.A.Q page too!

**Comment by tbartels** [comment]
There's already a block for that in the WP editor, feel free to use it. It probably needs some actual design applied to it in the long run.
